server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
    healthcheck:
      enabled: true
spring:
  application:
    name: taxi-service-paypal-service-2135353119
